<?php
/**
 * @copyright: Copyright © 2026 JOVEpay. All rights reserved.
 * @author   : JOVEpay <support@jovepay.com>
 */
// Retrieve order


$payemntData = $block->getPaymentData();
$quoteData   = $block->getQuote();
$themeMode = $payemntData['is_dark'] == "1" ? "dark" : "light";
$orderData = array();
$orderData['dataSource'] = "magento";
$orderData['ipnCallbackUrl'] = $block->getIpnUrl();
$orderData['priceCurrency'] = $payemntData['currency_code'];
$orderData['successUrl'] = $block->getSuccessUrl();
$orderData['cancelUrl'] = $block->getFailUrl();
$orderData['orderId'] = $block->getLastOrderId();
$orderData['apiKey'] = $payemntData['merchant_id'];
$orderData['isTestnet'] = $payemntData['is_testnet'] == "1" ? true : false;
$orderData['customerName'] = $quoteData->getCustomerFirstname() . ' ' . $quoteData->getCustomerLastname();
$orderData['customerEmail'] = $quoteData->getCustomerEmail();
$orderData['priceAmount'] = $quoteData->getBaseGrandTotal();
$orderData['shipping'] = $block->getShippingAmount();
$orderData['tax'] = $quoteData->getShippingAddress()->getTaxAmount();
$orderData['subtotal'] = $quoteData->getSubtotal();

//echo "<pre>"; print_r($quoteData->getData());

?>
<script type="text/javascript">
   require(['jquery'],function($){
        var orderData = '<?php echo urlencode(base64_encode(json_encode($orderData))) ?>';
        var PaymentURL = "https://www.jovepay.com/pay/payment/?theme=<?php echo $themeMode; ?>&params=";
        //console.log( orderData);
        window.location = PaymentURL + orderData; 
   });
</script>